name: Docker Image CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:     
  build_test_push:
    name: build_test_push
    permissions: write-all
    runs-on: ubuntu-latest 
    env:
      DOCKER_REPOSITORY: kennethfoo24 # name of Docker Hub ID
      
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 11
        distribution: temurin          
         
    - name: Build Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ${{ env.DOCKER_REPOSITORY }}/notes
        registry: docker.io
        tag: cloudrun
        dockerfile: cloudrun/dockerfile.cloudrun.notes.maven
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Build Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ${{ env.DOCKER_REPOSITORY }}/calendar
        registry: docker.io
        tag: cloudrun
        dockerfile: cloudrun/dockerfile.cloudrun.calendar.maven
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
